/**
 * Demo playlist data used when no real playlist is available.
 */
export const DEMO_PLAYLIST = {
  playlistTitle: '🎵 Plinder Demo Mix',
  playlistAuthor: 'Plinder',
  totalItems: 10,
  songs: [
    {
      id: 'dQw4w9WgXcQ',
      title: 'Rick Astley – Never Gonna Give You Up',
      author: 'Rick Astley',
      duration: '3:33',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    },
    {
      id: 'fJ9rUzIMcZQ',
      title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
      author: 'Queen Official',
      duration: '5:55',
      url: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
      thumbnail: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',
    },
    {
      id: 'ylwJOj_-_-A',
      title: 'Dua Lipa – Levitating (Official Music Video)',
      author: 'Dua Lipa',
      duration: '3:23',
      url: 'https://www.youtube.com/watch?v=ylwJOj_-_-A',
      thumbnail: 'https://i.ytimg.com/vi/ylwJOj_-_-A/hqdefault.jpg',
    },
    {
      id: 'H7ItmOe9bGk',
      title: 'The Weeknd – Blinding Lights (Official Music Video)',
      author: 'The Weeknd',
      duration: '3:22',
      url: 'https://www.youtube.com/watch?v=H7ItmOe9bGk',
      thumbnail: 'https://i.ytimg.com/vi/H7ItmOe9bGk/hqdefault.jpg',
    },
    {
      id: 'JGwWNGJdvx8',
      title: 'Ed Sheeran – Shape of You (Official Music Video)',
      author: 'Ed Sheeran',
      duration: '4:23',
      url: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
      thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg',
    },
    {
      id: 'ktvTqknDobU',
      title: 'Imagine Dragons – Radioactive (Official Music Video)',
      author: 'Imagine Dragons',
      duration: '3:06',
      url: 'https://www.youtube.com/watch?v=ktvTqknDobU',
      thumbnail: 'https://i.ytimg.com/vi/ktvTqknDobU/hqdefault.jpg',
    },
    {
      id: 'CevxZvSJLk8',
      title: 'Katy Perry – Roar (Official Music Video)',
      author: 'Katy Perry',
      duration: '4:32',
      url: 'https://www.youtube.com/watch?v=CevxZvSJLk8',
      thumbnail: 'https://i.ytimg.com/vi/CevxZvSJLk8/hqdefault.jpg',
    },
    {
      id: 'OPf0YbXqDm0',
      title: 'Mark Ronson ft. Bruno Mars – Uptown Funk (Official Video)',
      author: 'Mark Ronson',
      duration: '4:30',
      url: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
      thumbnail: 'https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg',
    },
    {
      id: 'hT_nvWreIhg',
      title: 'OneRepublic – Counting Stars (Official Music Video)',
      author: 'OneRepublic',
      duration: '4:17',
      url: 'https://www.youtube.com/watch?v=hT_nvWreIhg',
      thumbnail: 'https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg',
    },
    {
      id: '09R8_2nJtjg',
      title: 'Maroon 5 – Sugar (Official Music Video)',
      author: 'Maroon 5',
      duration: '3:55',
      url: 'https://www.youtube.com/watch?v=09R8_2nJtjg',
      thumbnail: 'https://i.ytimg.com/vi/09R8_2nJtjg/hqdefault.jpg',
    },
  ],
};
